os:
  - linux

before_script:
  - sudo add-apt-repository -y ppa:ubuntu-wine/ppa
  - sudo add-apt-repository -y ppa:rbose-debianizer/automake
  - sudo apt-get update -qq
  - sudo apt-get install -y autopoint
  - sudo apt-get install -y automake1.12
  - sudo apt-get install -y binutils-mingw-w64-i686
  - sudo apt-get install -y gcc-mingw-w64-i686 mingw-w64-tools

language: c

compiler:
  - gcc

script:
  - cd bzip2
  - git apply ../patches/*.txt
  - export CC=i686-w64-mingw32-gcc
  - export AR=i686-w64-mingw32-ar
  - export RANLIB=i686-w64-mingw32-ranlib
  - export RC=i686-w64-mingw32-windres
  - make
  - sudo apt-get install -y wine1.7
  - sudo update-binfmts --disable wine
  - sudo update-binfmts --enable wine
  - wineboot
  - export EXEEXT=.exe
  - export WINEDEBUG=-all
  - make winetest